<a href="https://colab.research.google.com/github/nsricharan/MLAssignment1/blob/main/Assignment1ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy**

Importing the Numpy

In [2]:
import numpy as np

Creating a random vector of size 15 having only Integers in the range 1-20.


In [ ]:
v1 = np.random.randint(1, 21, size=15)
print(v1)

Reshaping the array to 3 by 5

In [ ]:
v2 = v1.reshape(3, 5)
print(v2)

Printing the Array Shape

In [ ]:
print(v2.shape)

Replacing the max in each row by 0

In [ ]:
max_indices = np.argmax(v2, axis=1)
v2[np.arange(len(v2)), max_indices] = 0
print(v2)

Creating a 2-dimensional array of size 4 x 3 (composed of 4-byte integer elements), also print the shape, type and data type of the array

In [ ]:
import numpy as np

# Creating the array
ar = np.zeros((4, 3), dtype=np.int32)

# Print the shape, type, and data type
print("Shape:", ar.shape)
print("Type:", type(ar))
print("Data Type:", ar.dtype)

A program to compute the eigenvalues and right eigenvectors of a given square array given below:
[[ 3 -2]
[ 1 0]]

In [ ]:
# Array Declaration
arr1 = np.array([[3, -2], [1, 0]])

# Compute eigenvalues and eigenvectors
egvals, egvctr = np.linalg.eig(arr1)

# Print the results
print("Eigenvalues:", egvals)
print("Right Eigenvectors:")
for i, egvctr in enumerate(egvctr.T):
    print(f"Eigenvector {i+1}:", egvctr)


Sum of the diagonal element of a given array.
[[0 1 2]
[3 4 5]]

In [ ]:
#Array Declaration
arr2 = np.array([[0, 1, 2], [3, 4, 5]])

# Sum of diagonal elements
dg_sum = np.trace(arr2)

# Print the result
print("Sum of diagonal elements:", dg_sum)

Program to create a new shape to an array without changing its data.
Reshape 3x2:
[[1 2]
[3 4]
[5 6]]


In [ ]:
# Array Declaration
arr3 = np.array([[1, 2, 3], [4, 5, 6]])

# Reshape to 3x2
reshaped_arr = arr3.reshape(3, 2)

print("Reshaped Array:\n", reshaped_arr)

Reshape 2x3:
[[1 2 3]
[4 5 6]]

In [ ]:
# Reshape to 2x3
reshaped_arr2 = reshaped_arr.reshape(2,3)

print("Reshaped Array:\n", reshaped_arr2)

**Matplotlib**
1. Write a Python programming to create a below chart of the popularity of programming Languages.
2. Sample data:
Programming languages: Java, Python, PHP, JavaScript, C#, C++
Popularity: 22.2, 17.6, 8.8, 8, 7.7, 6.7

In [ ]:
import matplotlib.pyplot as plt

# Declaring the data
languages = ['Java', 'Python', 'PHP', 'JavaScript', 'C#', 'C++']
popularity = [22.2, 17.6, 8.8, 8, 7.7, 6.7]

# Designing a pie chart
plt.pie(popularity, labels=languages, autopct='%1.1f%%')

# Displaying the chart
plt.show()
